import os
import re
import sys

SHELL_PREFIX = re.compile(r'^([ \t\f\v]*)>[ \t\f\v]*')

SIGNATURE = ('# -*- coding: utf-8 -*-\n'
             '# This file was auto-generated by pysh.\n'
             '# Don\'t edit this by hand.\n')


# Needs to support here document and line concat with backslash.
def convert(r, w):
  for line in r.readlines():
    m = SHELL_PREFIX.match(line)
    if not m:
      w.write(line)
    else:
      indent = m.group(1)
      body = line[len(m.group(0)):]
      w.write(indent)
      w.write('pysh.pysh.run(%s, locals(), globals())' % `body.rstrip()`)
      w.write('\n')


def main():
  if len(sys.argv) < 2:
    print >> sys.stderr, 'Usage: pysh script.pysh'
    sys.exit(1)
  script = sys.argv[1]
  argv = sys.argv[2:]
  name, ext = os.path.splitext(script)
  if ext == ".py":
    print >> sys.stderr, 'An input file shoundn\'t be *.py.'
    sys.exit(1)
  py = name + '.py'
  r = file(script, 'r')
  w = file(py, 'w')
  w.write(SIGNATURE)
  w.write('import pysh.pysh\n')
  convert(r, w)
  w.close()
  os.execlp('python', 'python', py, *argv)


if __name__ == '__main__':
  main()
