#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import subprocess
import sys

tests = ['main_test.py',
         'pysh_test.py',
         ]

dir = os.path.dirname(os.path.realpath(__file__))
root = os.path.join(dir, '..')
path = os.environ.get('PYTHONPATH', '')
if path:
  path += ':'
os.environ['PYTHONPATH'] = path + root

print os.environ['PYTHONPATH']

result = {}

for test in tests:
  result[test] = subprocess.Popen(['python', os.path.join(dir, test)]).wait()

for test in result:
  if result[test] == 0:
    print '\033[32;1mSuccess:\033[m %s' % test
  else:
    print '\033[31;1mFailed :\033[m %s' % test
